fix[build]: add missing exception include on MacOS
This came up while I was running a build on macos, using

    ❯ clang --version
    clang version 21.1.8
    Target: arm64-apple-darwin
    Thread model: posix
    InstalledDir: /nix/store/10g0cwy9gcp4b0pw2znpgndbbzwdh1kv-clang-21.1.8/bin

and `/nix/store/9vcml00rc5xjhi1z4q1p8prpn91kpphl-libcxx-21.1.6+apple-sdk-26.4/`

This build error came up, and was resolved by this patch:

    FAILED: [code=1] src/3rdParty/salomesmesh/CMakeFiles/SMESH.dir/src/SMESH/Utils_ExceptHandlers.cpp.o

    In file included from /Users/user/dev/FreeCAD/src/3rdParty/salomesmesh/src/SMESH/Utils_ExceptHandlers.cpp:28:
    /Users/user/dev/FreeCAD/src/3rdParty/salomesmesh/inc/Utils_ExceptHandlers.hxx:55:20: error: no member named 'set_terminate' in namespace 'std'
       55 |       { old = std::set_terminate(f); }
          |                    ^~~~~~~~~~~~~
    /Users/user/dev/FreeCAD/src/3rdParty/salomesmesh/inc/Utils_ExceptHandlers.hxx:56:23: error: no type named 'set_terminate' in namespace 'std'
       56 |   ~Terminate() { std::set_terminate(old); }
          |                  ~~~~~^
    2 errors generated.

Assisted-by: GPT-6