PythonConsole: Enhance error reporting of Exceptions with dictionary input
==========================================================================

Problem:
When running interactive commands directly from the console (i.e. writting commands in the console),
Python exceptions having a dictionary (e.g. those raised with PyErr_SetObject and setting a PyDict as
object) are processed via a not thrown RuntimeError exception.

The current version disregards the what message of Exceptions with dictionary input, as the RunTimeError
is not initialised with it, and setPyObject does not handle the "swhat" dictionary input.

The outcome is that the generic FreeCAD message is printed:
>>> App.getDocument('partiallyRed').getObject('Sketch002').setDatum(14,App.Units.Quantity('-10.000000 mm'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: FreeCAD Exception

Solution:

To feed the RunTimeError exception with the swhat message, so that the exception is much more informative:

>>> App.getDocument('partiallyRed').getObject('Sketch002').setDatum(14,App.Units.Quantity('-10.000000 mm'))
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: Datum -10,000 mm for the constraint with index 14  is invalid