Exception: Enhance exceptions for dynamic string translations
=============================================================

Problem:
When strings are dynamically generated, it is currently not possible
to mark them for translation using QT_TRANSLATE_NOOP. The reason is
that the string marked with the macro will change (for example by
taking dynamically generated parameters).

The problem is that these strings will not be translated.

Solution:
- To extend Exception to store a formatter string suitable for
fmt::format, and string representations of the parameters.
- To extend Exceptions to be provided with a translator function
to assemble a translated error message when such translation is
necessary.