Fix build on MacOS-X 10.14: missing Xerces include dir
This undoes most of the Xerces related part of the commits listed below.
The issue resolved here is that the Xerces include dir *is* set in the
CMakeLists.txt of src/Base, but it got removed from various App and Gui
dirs in src/Mod. If those now include a header from src/Base, which
itself includes xercesc, the build fails using Apple clang version 11.0.0
(clang-1100.0.33.17) on Mojave, configured using cmake 3.22.1, with
errors like the following:

In file included from .../src/Mod/Part/App/FeaturePartBoolean.cpp:34:
In file included from .../src/App/Application.h:33:
.../src/Base/Parameter.h:54:10: fatal error: 'xercesc/util/XercesDefs.hpp' file not found
 #include <xercesc/util/XercesDefs.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

Finally, a full list of the commits that introduced this spurious include
dir optimization for reference:
- Drawing: commit 96ad045b91e4083782f5b7ef55e6479062c57d3b
- Image: commit dde71a21d52215ac036f3b57f82da7b7fe7ee3fc
- Import: commit c9d28b542fab87970137e2c8deb035235a857aba
- Inspection: commit d41f55f382c8e7907df3563fcba6c2e41b3415a7
- Mesh: commit 19072b05386835a2f9f76ffdb0737eae456cc0be
- Part: commit fe213a48f0598c79d8c127093d3edb585ddd58d3
- PartDesign: commit b037d8e240cb9e37319ef5a04445522793d4dc88
- Path: commit f23fa31f4287cda0289a41d7148b60479abf137f
- Points: commit bec723ba170ccbd24ec425fdf023cce7fe1be011
- Raytracing: commit 08d4ac63a33d4dbcfc52614a57cfaa79cb17955a
- ReverseEnginering: commit 5ca787cb0e13053b4523be8009d2e903ceab5d23
- Robot: commit bad4809a1c1c60e6223b6c6b68d30beb29c5c16f
- Sketcher: commit 3c96daf105a233f987aa408438d20938a495494b
- Spreadsheet: commit 66e8a2bef3f14424d288e4ab472eaa5343c1b55
- Start: commit c9dee5e70a46daaa59ac2e6f43a1600aca5af12b
- Surface: commit 6b04215be6b7d6daea28f90bed96b7589db18320
- TechDraw: commit 5e6699e48d577b21c86ca4bee0b778c14df330de
- Test: commit ea5b45b92c3055a04487a90c60572e081643c03b
- Web: commit ee6d631531faeff2bfb1180f74587e004320f240